In [1]:

import numpy as np

In [6]:
# 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes. 

arr1D=np.array([1,2,3,4,5])
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3D=np.array([
                [[1,2],[3,4],[5,6]],
                [[5,9],[10,11],[11,13]]
                ])

print(arr1D.ndim,arr1D.shape)
print(arr2D.ndim,arr2D.shape)
print(arr3D.ndim,arr3D.shape)



1 (5,)
2 (3, 3)
3 (2, 3, 2)


In [40]:
# 2 . Create: 
# ●  an array of zeros of shape (3,3)  
# ●  an array of ones of shape (2,5)  
# ●  an array filled with 7


zero=np.zeros((3,3))
print(zero)
one=np.ones((2,5))
print(one)
custom=np.full((3,3),7)
print(custom)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [12]:
# 3 . Create an array of even numbers between 10 and 50 using arange.

even=np.arange(10,50,2)
print(even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [30]:
# 4 . Create a 4×4 matrix from 0–15. Then , extract: 
# ●  the first row  
# ●  the last column  
# ●  a 2×2 subarray from the center

arr=np.random.randint(0,15,(4,4))
print(arr,end="\n\n")
print(arr[0:1,],end="\n\n")
print(arr[::,-1],end="\n\n")
print(arr[1:3:1,1:3:1])

[[ 7  5 10 11]
 [14  1 14 12]
 [ 2 10 13  6]
 [ 5 13  8 13]]

[[ 7  5 10 11]]

[11 12  6 13]

[[ 1 14]
 [10 13]]


In [43]:
# 5.Add a 1D array [1,2,3] to each row of a 3×3 matrix.

add_value=np.array([1,2,3])

new_custom=custom+add_value
print(new_custom)

[[ 8  9 10]
 [ 8  9 10]
 [ 8  9 10]]


In [45]:
# 6 . Given two arrays A and B, compute: 
# ●  (A + B) / 2  
# ●  A**2 + B**2

A=custom
B=new_custom

print((A+B)/2)
print()
print(A**2+B**2)

[[7.5 8.  8.5]
 [7.5 8.  8.5]
 [7.5 8.  8.5]]

[[113 130 149]
 [113 130 149]
 [113 130 149]]
